2022-08-07 12:55:08,070 Watching for file changes with StatReloader
2022-08-07 13:00:49,116 Requested users/new/
2022-08-07 13:01:18,592 Requested users/new/
2022-08-07 13:01:47,408 {'role': ['Value 3 is not a valid choice.']}
2022-08-07 13:01:47,408 Requested users/new/
2022-08-07 13:01:47,446 Internal Server Error: /users/new/
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/src/skrate_ticketing/users/views.py", line 20, in create_user
    new_user.save()
  File "/home/kaushik/work/skrate/src/skrate_ticketing/users/models.py", line 36, in save
    self.clean_fields()
  File "/home/kaushik/work/skrate/src/skrate_ticketing/users/models.py", line 25, in clean_fields
    super().clean_fields(exclude=exclude)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/db/models/base.py", line 1521, in clean_fields
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'role': ['Value 3 is not a valid choice.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/kaushik/work/skrate/src/skrate_ticketing/users/views.py", line 27, in create_user
    raise http_409_conflict(message=e.message)
AttributeError: 'ValidationError' object has no attribute 'message'
2022-08-07 13:02:29,993 /home/kaushik/work/skrate/src/skrate_ticketing/users/views.py changed, reloading.
2022-08-07 13:02:30,494 Watching for file changes with StatReloader
2022-08-07 13:02:35,244 {'role': ['Value 3 is not a valid choice.']}
2022-08-07 13:02:35,244 Requested users/new/
2022-08-07 13:02:35,245 Internal Server Error: /users/new/
2022-08-07 13:04:50,431 Requested users/new/
2022-08-07 13:05:23,304 Requested users/new/
2022-08-07 13:05:46,552 {'role': ['Value 3 is not a valid choice.']}
2022-08-07 13:05:46,553 Requested users/new/
2022-08-07 13:05:46,553 Internal Server Error: /users/new/
2022-08-07 13:10:14,873 Requested tickets/new/
2022-08-07 13:10:39,743 Internal Server Error: /tickets/new/
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kaushik/work/skrate/src/skrate_ticketing/tickets/decorator.py", line 34, in _view
    raise http_401_unauthorized()
rest_framework.exceptions.APIException: Unauthorized
2022-08-07 13:11:10,587 /home/kaushik/work/skrate/src/skrate_ticketing/users/views.py changed, reloading.
2022-08-07 13:11:11,504 Watching for file changes with StatReloader
2022-08-07 13:11:35,746 Internal Server Error: /tickets/new/
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kaushik/work/skrate/src/skrate_ticketing/tickets/decorator.py", line 34, in _view
    raise http_401_unauthorized()
rest_framework.exceptions.APIException: Unauthorized
2022-08-07 13:12:16,681 /home/kaushik/work/skrate/src/skrate_ticketing/tickets/decorator.py changed, reloading.
2022-08-07 13:12:17,040 Watching for file changes with StatReloader
2022-08-07 13:12:21,209 Internal Server Error: /tickets/new/
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_response(request, response)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'bool' object has no attribute 'get'
2022-08-07 13:12:36,771 /home/kaushik/work/skrate/src/skrate_ticketing/tickets/decorator.py changed, reloading.
2022-08-07 13:12:37,088 Watching for file changes with StatReloader
2022-08-07 13:12:53,837 Internal Server Error: /tickets/new/
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kaushik/work/skrate/src/skrate_ticketing/tickets/decorator.py", line 35, in _view
    raise http_401_unauthorized()
rest_framework.exceptions.APIException: Unauthorized
2022-08-07 13:13:50,067 /home/kaushik/work/skrate/src/skrate_ticketing/tickets/decorator.py changed, reloading.
2022-08-07 13:13:50,563 Watching for file changes with StatReloader
2022-08-07 13:15:45,510 /home/kaushik/work/skrate/src/skrate_ticketing/users/views.py changed, reloading.
2022-08-07 13:15:45,819 Watching for file changes with StatReloader
2022-08-07 13:18:41,050 Requested users/new/
2022-08-07 13:19:02,804 Requested users/new/
2022-08-07 13:19:22,150 {'role': ['Value 3 is not a valid choice.']}
2022-08-07 13:19:22,150 Requested users/new/
2022-08-07 13:19:22,150 Internal Server Error: /users/new/
2022-08-07 13:19:42,685 ["Username 'emp user' is already in use."]
2022-08-07 13:19:42,685 Requested users/new/
2022-08-07 13:19:42,686 Internal Server Error: /users/new/
2022-08-07 13:23:21,034 Requested tickets/new/
2022-08-07 13:24:08,566 Requested tickets/all/
2022-08-07 13:24:32,020 Requested tickets/all/
2022-08-07 13:24:39,243 Requested tickets/all/
2022-08-07 13:24:51,696 Internal Server Error: /tickets/all/
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kaushik/work/skrate/src/skrate_ticketing/tickets/decorator.py", line 12, in _view
    token = request.headers["Authorization"].split()[-1]
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/http/request.py", line 437, in __getitem__
    return super().__getitem__(key.replace("_", "-"))
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/datastructures.py", line 309, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'authorization'
2022-08-07 13:25:13,272 Requested tickets/all/
2022-08-07 13:25:53,057 Requested tickets/?status=&title=&priority
2022-08-07 13:27:53,742 Requested tickets/maskAsClosed/
2022-08-07 13:28:54,479 Ticket matching query does not exist.
2022-08-07 13:28:54,480 Requested tickets/delete/
2022-08-07 13:28:54,480 Internal Server Error: /tickets/delete/
2022-08-07 13:29:02,739 Ticket matching query does not exist.
2022-08-07 13:29:02,740 Requested tickets/delete/
2022-08-07 13:29:02,740 Internal Server Error: /tickets/delete/
2022-08-07 13:29:19,691 Requested tickets/?status=&title=&priority
2022-08-07 13:30:06,173 Requested tickets/delete/
2022-08-07 14:22:00,726 Watching for file changes with StatReloader
2022-08-07 14:22:03,740 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2022-08-07 14:22:03,796 Bad Request: /
2022-08-07 14:22:03,971 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2022-08-07 14:22:04,003 Bad Request: /favicon.ico
2022-08-07 14:22:09,372 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2022-08-07 14:22:09,413 Bad Request: /docs
2022-08-07 14:22:09,575 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2022-08-07 14:22:09,622 Bad Request: /favicon.ico
2022-08-07 14:22:17,157 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2022-08-07 14:22:17,201 Bad Request: /tickets/all
2022-08-07 14:22:17,361 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2022-08-07 14:22:17,389 Bad Request: /favicon.ico
2022-08-07 14:22:32,751 /home/kaushik/work/skrate/src/skrate_ticketing/skrate_ticketing/settings.py changed, reloading.
2022-08-07 14:22:33,057 Watching for file changes with StatReloader
2022-08-07 14:22:36,327 /home/kaushik/work/skrate/src/skrate_ticketing/skrate_ticketing/settings.py changed, reloading.
2022-08-07 14:22:36,817 Watching for file changes with StatReloader
2022-08-07 14:22:37,744 Internal Server Error: /tickets/all/
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kaushik/work/skrate/src/skrate_ticketing/tickets/decorator.py", line 12, in _view
    token = request.headers["Authorization"].split()[-1]
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/http/request.py", line 437, in __getitem__
    return super().__getitem__(key.replace("_", "-"))
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/datastructures.py", line 309, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'authorization'
2022-08-07 14:22:37,920 Not Found: /favicon.ico
2022-08-07 14:22:48,428 /home/kaushik/work/skrate/src/skrate_ticketing/skrate_ticketing/settings.py changed, reloading.
2022-08-07 14:22:48,970 Watching for file changes with StatReloader
2022-08-07 14:25:29,823 /home/kaushik/work/skrate/src/skrate_ticketing/tickets/views.py changed, reloading.
2022-08-07 14:25:30,178 Watching for file changes with StatReloader
2022-08-07 14:25:30,448 Requested tickets/all/
2022-08-07 14:25:34,345 Requested tickets/all/
2022-08-07 14:25:37,533 Requested tickets/all/
2022-08-07 14:25:42,734 Requested tickets/all/
2022-08-07 14:25:55,990 Requested tickets/all/
2022-08-07 14:26:07,743 Method Not Allowed: /users/new/
2022-08-07 14:26:12,990 Internal Server Error: /tickets/
Traceback (most recent call last):
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kaushik/work/skrate/src/skrate_ticketing/tickets/decorator.py", line 12, in _view
    token = request.headers["Authorization"].split()[-1]
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/http/request.py", line 437, in __getitem__
    return super().__getitem__(key.replace("_", "-"))
  File "/home/kaushik/work/skrate/venv-skrate/lib/python3.10/site-packages/django/utils/datastructures.py", line 309, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'authorization'
2022-08-07 14:26:24,233 Method Not Allowed: /users/new/
2022-08-07 14:36:54,845 /home/kaushik/work/skrate/src/skrate_ticketing/skrate_ticketing/settings.py changed, reloading.
2022-08-07 14:36:55,383 Watching for file changes with StatReloader
2022-08-07 14:37:06,936 /home/kaushik/work/skrate/src/skrate_ticketing/tickets/views.py changed, reloading.
2022-08-07 14:37:07,467 Watching for file changes with StatReloader
2022-08-07 14:41:16,840 /home/kaushik/work/skrate/src/skrate_ticketing/skrate_ticketing/settings.py changed, reloading.
2022-08-07 14:41:17,402 Watching for file changes with StatReloader
2022-08-07 14:41:28,194 Method Not Allowed: /users/new/
2022-08-07 14:41:28,381 Not Found: /favicon.ico
2022-08-07 14:46:51,711 /home/kaushik/work/skrate/src/skrate_ticketing/skrate_ticketing/urls.py changed, reloading.
2022-08-07 14:46:52,896 Watching for file changes with StatReloader
2022-08-07 14:47:11,780 /home/kaushik/work/skrate/src/skrate_ticketing/skrate_ticketing/urls.py changed, reloading.
2022-08-07 14:47:12,097 Watching for file changes with StatReloader
2022-08-07 14:48:14,932 /home/kaushik/work/skrate/src/skrate_ticketing/skrate_ticketing/settings.py changed, reloading.
2022-08-07 14:48:15,425 Watching for file changes with StatReloader
